### ISSUE TITLE
Do I need to install rtw88-dkms-git to install/build rtl8xxxu on arch?

### ISSUE THREAD

**Issue by anon62** [lwfinger/rtl8xxxu#4]
According to readme

**Comment by lwfinger** [comment]
No, dkms is not required. I suggest you do some reading on what dkms actually does and decide if you want it. BTW, I have dealt with out-of-kernel modules for about 15 years, and never once implemented dkms.

**Comment by anon62** [comment]
> No, dkms is not required. I suggest you do some reading on what dkms actually does and decide if you want it. BTW, I have dealt with out-of-kernel modules for about 15 years, and never once implemented dkms.

I don't mean whether I need dkms, I mean whether I need to install a "rtw88" called "rtw88-dkms-git" on AUR to install rtl8xxxu as written in the readme:

```
For **Arch**: After installing the necessary kernel headers and base-devel,
```
```
    git clone https://aur.archlinux.org/rtw88-dkms-git.git
    cd rtw88-dkms-git
    makepkg -sri
```

**Comment by anon62** [comment]
It's just strange that rtl8xxxxu doesn't require rtw88 on other distributions
