### ISSUE TITLE
[Question] How to check if it works?

### ISSUE THREAD

**Issue by nicola02nb** [lwfinger/rtl8xxxu#6]
I've executed all installation steps without getting any error on Debian 11, how do i check if it works?

I'm kind a newbie on this.

**Comment by dubhater** [comment]
You can check ``iw dev``. It should show an interface that wasn't there before.

**Comment by nicola02nb** [comment]
I doesn't show any device... I'll guess it isn't working

**Comment by dubhater** [comment]
Maybe you have not loaded the module yet: ``sudo modprobe rtl8xxxu_git``

**Comment by lwfinger** [comment]
If loading the module does not help, then check the logs. 'sudo dmesg | less' will get you those. Look for missing firmware, etc.

**Comment by nicola02nb** [comment]
> Maybe you have not loaded the module yet: `sudo modprobe rtl8xxxu_git`

The module is loaded, and I can see it with `lsmod | grep rtl8xxxu`

**Comment by nicola02nb** [comment]
> If loading the module does not help, then check the logs. 'sudo dmesg | less' will get you those. Look for missing firmware, etc.

I haven't found nothing I think is relevant yet, if you want I can provide the all log form `dmesg`

**Comment by dubhater** [comment]
The full output from dmesg would be very helpful.

**Comment by nicola02nb** [comment]
That's the log.

[dmesg.txt](https://github.com/lwfinger/rtl8xxxu/files/14222181/dmesg.txt)

**Comment by dubhater** [comment]
rtl8xxxu does not handle 0bda:c811. You need either https://github.com/lwfinger/rtw88 or https://github.com/morrownr/8821cu-20210916

I have a Tenda U9 with the same USB ID as your device, and it doesn't work with rtw88. It can't connect to my network. If you have that problem too, the other driver will work.

**Comment by nicola02nb** [comment]
Oh, but when I do `lsusb` it reports as model RTL8188GU ....

Tho I worked it out with the second one ([https://github.com/morrownr/8821cu-20210916](https://github.com/morrownr/8821cu-20210916)), thanks.

**Comment by lwfinger** [comment]
Is it advertised as a "Wifi 5" card? In that case, rtw88 is the proper directory. ID 0bda:c811 is an RTW8821CU. That ID should not be included in rtl8xxxu.

**Comment by nicola02nb** [comment]
Yes, it's advertised as Wifi 5.
As I said, it actually works with the 8821cu.

Thanks for all your help
